name: "Build & publish sshelter-client release"

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - run: GOOS=linux GOARCH=amd64 go build -ldflags="-X utils.VERSION=${GITHUB_REF##*/} -X utils.COMMIT=${GITHUB_SHA}" -o sshelter-${GITHUB_REF##*/}-linux-x86_64 .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "sshelter-*-*-*"
          token: ${{ secrets.GITHUB_TOKEN }}